permissions:
  contents: write

name: Thesis work Tests

on:
  schedule:
      - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run tests with PYTHONPATH
        run: |
          PYTHONPATH=. pytest tests/ > own_test_results.txt || true

      - name: Run Pom and test generator
        run: |
          PYTHONPATH=. pytest generated_poms_and_test/ai_code_generator.py > ai_generator.txt || true

      - name: Commit the changes to repo
        run: |
          git config --global user.name "csabida01"
          git config --global user.email "csabida01@users.noreply.github.com"
          git add generated_poms_and_test/
          git commit -m "Update generated POMs and tests" || echo "No changes to commit"
          git push https://csabida01:${{ secrets.GH_PAT }}@github.com/csabida01/KCS_thesis_CICD.git

      - name: Run AI test
        run: |
          PYTHONPATH=. pytest generated_poms_and_test/generated_test_main.py > ai_test_results.txt || true

      - name: Combine the logs
        run: |
          cat own_test_results.txt ai_generator.txt ai_test_results.txt > full_test_pipeline_results.txt

      - name: Send test results via email
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Test Report"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Szia!

            Itt vannak a lefuttatott teszt eredmények.

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Status: ${{ job.status }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Üdv,
            Github Actions
          attachments: full_test_pipeline_results.txt